# Cloud Build configuration for k0sNgin
# This builds the Docker image and can optionally deploy to Cloud Run
#
# To use:
#   gcloud builds submit --config cloudbuild.yaml
#
# Or trigger from Git:
#   gcloud builds triggers create github \
#     --repo-name=k0sNgin \
#     --repo-owner=<your-org> \
#     --branch-pattern="^main$" \
#     --build-config=cloudbuild.yaml

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/k0sninja:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/k0sninja:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/k0sninja'

  # (Optional) Deploy to Cloud Run
  # Uncomment the following step to auto-deploy after build
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       cd infra/terraform
  #       terraform init
  #       terraform apply -auto-approve

images:
  - 'gcr.io/$PROJECT_ID/k0sninja:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/k0sninja:latest'

options:
  logging: CLOUD_LOGGING_ONLY
